var snippetParts = [
	{
		title: 'echo.php',
		content: "<?php echo 'hello'; ?>",
		language: 'PHP'
	},
	{
		title: 'script.js',
		content: "console.log('hello !');",
		language: 'JavaScript'
	},
	{
		title: 'index.html',
		content: "<h1>Foo bar</h1>",
		language: 'HTML'
	}
];

var languages = [
	{ name: 'Ada', aceEditorMode: 'ada' },
	{ name: 'Apache conf', aceEditorMode: 'apache_conf' },
	{ name: 'AppleScript', aceEditorMode: 'applescript' },
	{ name: 'ASCIIDoc', aceEditorMode: 'asciidoc' },
	{ name: 'Assembly x86', aceEditorMode: 'assembly_x86' },
	{ name: 'AutoHotkey', aceEditorMode: 'autohotkey' },
	{ name: 'Batch file', aceEditorMode: 'batchfile' },
	{ name: 'BroCode', aceEditorMode: 'bro' },
	{ name: 'C9 Search', aceEditorMode: 'c9search' },
	{ name: 'C/C++', aceEditorMode: 'c_cpp' },
	{ name: 'Cirru', aceEditorMode: 'cirru' },
	{ name: 'Clojure', aceEditorMode: 'clojure' },
	{ name: 'Cobol', aceEditorMode: 'cobol' },
	{ name: 'CoffeeScript', aceEditorMode: 'coffee' },
	{ name: 'ColdFusion', aceEditorMode: 'coldfusion' },
	{ name: 'C#', aceEditorMode: 'csharp' },
	{ name: 'CSS', aceEditorMode: 'css' },
	{ name: 'Curl', aceEditorMode: 'curly' },
	{ name: 'Dart', aceEditorMode: 'dart' },
	{ name: 'Django', aceEditorMode: 'django' },
	{ name: 'D', aceEditorMode: 'd' },
	{ name: 'Dockerfile', aceEditorMode: 'dockerfile' },
	{ name: 'DOT', aceEditorMode: 'dot' },
	{ name: 'Drools', aceEditorMode: 'drools' },
	{ name: 'Eiffel', aceEditorMode: 'eiffel' },
	{ name: 'EJS', aceEditorMode: 'ejs' },
	{ name: 'Elixir', aceEditorMode: 'elixir' },
	{ name: 'Elm', aceEditorMode: 'elm' },
	{ name: 'Erlang', aceEditorMode: 'erlang' },
	{ name: 'Forth', aceEditorMode: 'forth' },
	{ name: 'Fortran', aceEditorMode: 'fortran' },
	{ name: 'FTL', aceEditorMode: 'ftl' },
	{ name: 'G-code', aceEditorMode: 'gcode' },
	{ name: 'Gherkin', aceEditorMode: 'gherkin' },
	{ name: 'gitignore', aceEditorMode: 'gitignore' },
	{ name: 'GLSL', aceEditorMode: 'glsl' },
	{ name: 'Gobstones', aceEditorMode: 'gobstones' },
	{ name: 'Go', aceEditorMode: 'golang' },
	{ name: 'Groovy', aceEditorMode: 'groovy' },
	{ name: 'Haml', aceEditorMode: 'haml' },
	{ name: 'Handlebars', aceEditorMode: 'handlebars' },
	{ name: 'Haskell Cabal', aceEditorMode: 'haskell_cabal' },
	{ name: 'Haskell', aceEditorMode: 'haskell' },
	{ name: 'Haxe', aceEditorMode: 'haxe' },
	{ name: 'Hjson', aceEditorMode: 'hjson' },
	{ name: 'HTML Elixir', aceEditorMode: 'html_elixir' },
	{ name: 'HTML', aceEditorMode: 'html' },
	{ name: 'HTML Ruby', aceEditorMode: 'html_ruby' },
	{ name: 'INI', aceEditorMode: 'ini' },
	{ name: 'Io', aceEditorMode: 'io' },
	{ name: 'Jack', aceEditorMode: 'jack' },
	{ name: 'JADE', aceEditorMode: 'jade' },
	{ name: 'Java', aceEditorMode: 'java' },
	{ name: 'JavaScript', aceEditorMode: 'javascript' },
	{ name: 'JSONiq', aceEditorMode: 'jsoniq' },
	{ name: 'JSON', aceEditorMode: 'json' },
	{ name: 'JSP', aceEditorMode: 'jsp' },
	{ name: 'JSX', aceEditorMode: 'jsx' },
	{ name: 'Julia', aceEditorMode: 'julia' },
	{ name: 'Kotlin', aceEditorMode: 'kotlin' },
	{ name: 'LaTeX', aceEditorMode: 'latex' },
	{ name: 'Less', aceEditorMode: 'less' },
	{ name: 'Liquid', aceEditorMode: 'liquid' },
	{ name: 'Lisp', aceEditorMode: 'lisp' },
	{ name: 'LogiQL', aceEditorMode: 'logiql' },
	{ name: 'LSL', aceEditorMode: 'lsl' },
	{ name: 'Lua', aceEditorMode: 'lua' },
	{ name: 'Lua Page', aceEditorMode: 'luapage' },
	{ name: 'Lucene', aceEditorMode: 'lucene' },
	{ name: 'Makefile', aceEditorMode: 'makefile' },
	{ name: 'Markdown', aceEditorMode: 'markdown' },
	{ name: 'Mask', aceEditorMode: 'mask' },
	{ name: 'MATLAB', aceEditorMode: 'matlab' },
	{ name: 'Maze', aceEditorMode: 'maze' },
	{ name: 'MEL', aceEditorMode: 'mel' },
	{ name: 'MUSHCode', aceEditorMode: 'mushcode' },
	{ name: 'MySQL', aceEditorMode: 'mysql' },
	{ name: 'Nix', aceEditorMode: 'nix' },
	{ name: 'NSIS', aceEditorMode: 'nsis' },
	{ name: 'Objective-C', aceEditorMode: 'objectivec' },
	{ name: 'OCaml', aceEditorMode: 'ocaml' },
	{ name: 'Pascal', aceEditorMode: 'pascal' },
	{ name: 'Perl', aceEditorMode: 'perl' },
	{ name: 'PostgreSQL', aceEditorMode: 'pgsql' },
	{ name: 'PHP', aceEditorMode: 'php' },
	{ name: 'PowerShell', aceEditorMode: 'powershell' },
	{ name: 'Praat', aceEditorMode: 'praat' },
	{ name: 'Prolog', aceEditorMode: 'prolog' },
	{ name: 'Properties', aceEditorMode: 'properties' },
	{ name: 'Protobuf', aceEditorMode: 'protobuf' },
	{ name: 'Python', aceEditorMode: 'python' },
	{ name: 'Razor', aceEditorMode: 'razor' },
	{ name: 'RDoc', aceEditorMode: 'rdoc' },
	{ name: 'R HTML', aceEditorMode: 'rhtml' },
	{ name: 'R', aceEditorMode: 'r' },
	{ name: 'RST', aceEditorMode: 'rst' },
	{ name: 'Ruby', aceEditorMode: 'ruby' },
	{ name: 'Rust', aceEditorMode: 'rust' },
	{ name: 'Sass', aceEditorMode: 'sass' },
	{ name: 'OpenSCAD', aceEditorMode: 'scad' },
	{ name: 'Scala', aceEditorMode: 'scala' },
	{ name: 'Scheme', aceEditorMode: 'scheme' },
	{ name: 'SCSS', aceEditorMode: 'scss' },
	{ name: 'Shell', aceEditorMode: 'sh' },
	{ name: 'SJS', aceEditorMode: 'sjs' },
	{ name: 'Smarty', aceEditorMode: 'smarty' },
	{ name: 'Snippets', aceEditorMode: 'snippets' },
	{ name: 'Soy template', aceEditorMode: 'soy_template' },
	{ name: 'Whitespace', aceEditorMode: 'space' },
	{ name: 'SQL', aceEditorMode: 'sql' },
	{ name: 'SQL Server', aceEditorMode: 'sqlserver' },
	{ name: 'Stylus', aceEditorMode: 'stylus' },
	{ name: 'SVG', aceEditorMode: 'svg' },
	{ name: 'Swift', aceEditorMode: 'swift' },
	{ name: 'Tcl', aceEditorMode: 'tcl' },
	{ name: 'TeX', aceEditorMode: 'tex' },
	{ name: 'Textile', aceEditorMode: 'textile' },
	{ name: 'TOML', aceEditorMode: 'toml' },
	{ name: 'TSX', aceEditorMode: 'tsx' },
	{ name: 'Twig', aceEditorMode: 'twig' },
	{ name: 'TypeScript', aceEditorMode: 'typescript' },
	{ name: 'Vala', aceEditorMode: 'vala' },
	{ name: 'VBScript', aceEditorMode: 'vbscript' },
	{ name: 'Velocity', aceEditorMode: 'velocity' },
	{ name: 'Verilog', aceEditorMode: 'verilog' },
	{ name: 'VHDL', aceEditorMode: 'vhdl' },
	{ name: 'Wollok', aceEditorMode: 'wollok' },
	{ name: 'XML', aceEditorMode: 'xml' },
	{ name: 'XQuery', aceEditorMode: 'xquery' },
	{ name: 'YAML', aceEditorMode: 'yaml' },
	{ name: 'ABAP', aceEditorMode: 'abap' },
	{ name: 'ABC', aceEditorMode: 'abc' },
	{ name: 'ActionScript', aceEditorMode: 'actionscript' },
	{ name: 'Lean', aceEditorMode: 'lean' },
	{ name: 'Live Script', aceEditorMode: 'live_script' },
	{ name: 'LiveScript', aceEditorMode: 'livescript' },
	{ name: 'MavensMate', aceEditorMode: 'mavens_mate_log' },
	{ name: 'MIPS Assembly', aceEditorMode: 'mips_assembler' },
	{ name: 'MIPSAssembly', aceEditorMode: 'mipsassembler' },
	{ name: 'SWIG', aceEditorMode: 'swig' },
	{ name: 'Diff', aceEditorMode: 'diff' },
	{ name: 'Plain Text', aceEditorMode: 'plain_text' },
	{ name: 'Text', aceEditorMode: 'text' }
];

var tags = [
	{ name : 'Aaa'},
	{ name : 'Bbb'},
	{ name : 'Ccc'},
	{ name : 'Ddd'},
	{ name : 'Eee'},
	{ name : 'Fff'}
];

var snippets = [
	{
		title: 'Optional description',
		// preview: "console.log('test 1');",
		description: ''
		// parts : snippetParts
	},
	{
		title: 'Public gist.test.py',
		// preview: "console.log('test 2');",
		description: 'test 2 description with **bold text**',
		starred: true,
		// parts : snippetParts
	},
	{
		title: 'Private snippet',
		'private' : true,
		// preview: "console.log('test 3');",
		description: 'test 3 description with **bold text**'
		// parts : snippetParts
	},
	{
		title: 'dTest 4',
		// preview: "console.log('test 4');",
		description: 'test 4 description with **bold text**'
		// parts : snippetParts
	}
];

var users = [
	{
		username: 'test UFO',
    passwordHash: '$2b$10$lHuDgPYu5W8vo7wGemrWoOZDmdvPjrWx83C6cd/Toqut4E7CITY1i',
		email: 'mail@test.com',
		githubUsername: 'UFOcatcher'
	},
	{
		username: 'test',
    passwordHash: '$2b$10$lHuDgPYu5W8vo7wGemrWoOZDmdvPjrWx83C6cd/Toqut4E7CITY1i',
		email: 'usertest@test.com',
		githubUsername: ''
	}
];

module.exports = {snippets : snippets, snippetParts : snippetParts, tags: tags, languages : languages, users: users};
