var snippetParts = [
	{
		title: 'echo.php',
		content: "<?php echo 'hello'; ?>",
		language: 'PHP'
	},
	{
		title: 'script.js',
		content: "console.log('hello !');",
		language: 'JavaScript'
	},
	{
		title: 'index.html',
		content: "<h1>Foo bar</h1>",
		language: 'HTML'
	}
];

var languages = [
	{ name: 'Ada', aceEditorPlugin: 'ada' },
	{ name: 'Apache conf', aceEditorPlugin: 'apache_conf' },
	{ name: 'AppleScript', aceEditorPlugin: 'applescript' },
	{ name: 'ASCIIDoc', aceEditorPlugin: 'asciidoc' },
	{ name: 'Assembly x86', aceEditorPlugin: 'assembly_x86' },
	{ name: 'AutoHotkey', aceEditorPlugin: 'autohotkey' },
	{ name: 'Batch file', aceEditorPlugin: 'batchfile' },
	{ name: 'BroCode', aceEditorPlugin: 'bro' },
	{ name: 'C9 Search', aceEditorPlugin: 'c9search' },
	{ name: 'C/C++', aceEditorPlugin: 'c_cpp' },
	{ name: 'Cirru', aceEditorPlugin: 'cirru' },
	{ name: 'Clojure', aceEditorPlugin: 'clojure' },
	{ name: 'Cobol', aceEditorPlugin: 'cobol' },
	{ name: 'CoffeeScript', aceEditorPlugin: 'coffee' },
	{ name: 'ColdFusion', aceEditorPlugin: 'coldfusion' },
	{ name: 'C#', aceEditorPlugin: 'csharp' },
	{ name: 'CSS', aceEditorPlugin: 'css' },
	{ name: 'Curl', aceEditorPlugin: 'curly' },
	{ name: 'Dart', aceEditorPlugin: 'dart' },
	{ name: 'Django', aceEditorPlugin: 'django' },
	{ name: 'D', aceEditorPlugin: 'd' },
	{ name: 'Dockerfile', aceEditorPlugin: 'dockerfile' },
	{ name: 'DOT', aceEditorPlugin: 'dot' },
	{ name: 'Drools', aceEditorPlugin: 'drools' },
	{ name: 'Eiffel', aceEditorPlugin: 'eiffel' },
	{ name: 'EJS', aceEditorPlugin: 'ejs' },
	{ name: 'Elixir', aceEditorPlugin: 'elixir' },
	{ name: 'Elm', aceEditorPlugin: 'elm' },
	{ name: 'Erlang', aceEditorPlugin: 'erlang' },
	{ name: 'Forth', aceEditorPlugin: 'forth' },
	{ name: 'Fortran', aceEditorPlugin: 'fortran' },
	{ name: 'FTL', aceEditorPlugin: 'ftl' },
	{ name: 'G-code', aceEditorPlugin: 'gcode' },
	{ name: 'Gherkin', aceEditorPlugin: 'gherkin' },
	{ name: 'gitignore', aceEditorPlugin: 'gitignore' },
	{ name: 'GLSL', aceEditorPlugin: 'glsl' },
	{ name: 'Gobstones', aceEditorPlugin: 'gobstones' },
	{ name: 'Go', aceEditorPlugin: 'golang' },
	{ name: 'Groovy', aceEditorPlugin: 'groovy' },
	{ name: 'Haml', aceEditorPlugin: 'haml' },
	{ name: 'Handlebars', aceEditorPlugin: 'handlebars' },
	{ name: 'Haskell Cabal', aceEditorPlugin: 'haskell_cabal' },
	{ name: 'Haskell', aceEditorPlugin: 'haskell' },
	{ name: 'Haxe', aceEditorPlugin: 'haxe' },
	{ name: 'Hjson', aceEditorPlugin: 'hjson' },
	{ name: 'HTML Elixir', aceEditorPlugin: 'html_elixir' },
	{ name: 'HTML', aceEditorPlugin: 'html' },
	{ name: 'HTML Ruby', aceEditorPlugin: 'html_ruby' },
	{ name: 'INI', aceEditorPlugin: 'ini' },
	{ name: 'Io', aceEditorPlugin: 'io' },
	{ name: 'Jack', aceEditorPlugin: 'jack' },
	{ name: 'JADE', aceEditorPlugin: 'jade' },
	{ name: 'Java', aceEditorPlugin: 'java' },
	{ name: 'JavaScript', aceEditorPlugin: 'javascript' },
	{ name: 'JSONiq', aceEditorPlugin: 'jsoniq' },
	{ name: 'JSON', aceEditorPlugin: 'json' },
	{ name: 'JSP', aceEditorPlugin: 'jsp' },
	{ name: 'JSX', aceEditorPlugin: 'jsx' },
	{ name: 'Julia', aceEditorPlugin: 'julia' },
	{ name: 'Kotlin', aceEditorPlugin: 'kotlin' },
	{ name: 'LaTeX', aceEditorPlugin: 'latex' },
	{ name: 'Less', aceEditorPlugin: 'less' },
	{ name: 'Liquid', aceEditorPlugin: 'liquid' },
	{ name: 'Lisp', aceEditorPlugin: 'lisp' },
	{ name: 'LogiQL', aceEditorPlugin: 'logiql' },
	{ name: 'LSL', aceEditorPlugin: 'lsl' },
	{ name: 'Lua', aceEditorPlugin: 'lua' },
	{ name: 'Lua Page', aceEditorPlugin: 'luapage' },
	{ name: 'Lucene', aceEditorPlugin: 'lucene' },
	{ name: 'Makefile', aceEditorPlugin: 'makefile' },
	{ name: 'Markdown', aceEditorPlugin: 'markdown' },
	{ name: 'Mask', aceEditorPlugin: 'mask' },
	{ name: 'MATLAB', aceEditorPlugin: 'matlab' },
	{ name: 'Maze', aceEditorPlugin: 'maze' },
	{ name: 'MEL', aceEditorPlugin: 'mel' },
	{ name: 'MUSHCode', aceEditorPlugin: 'mushcode' },
	{ name: 'MySQL', aceEditorPlugin: 'mysql' },
	{ name: 'Nix', aceEditorPlugin: 'nix' },
	{ name: 'NSIS', aceEditorPlugin: 'nsis' },
	{ name: 'Objective-C', aceEditorPlugin: 'objectivec' },
	{ name: 'OCaml', aceEditorPlugin: 'ocaml' },
	{ name: 'Pascal', aceEditorPlugin: 'pascal' },
	{ name: 'Perl', aceEditorPlugin: 'perl' },
	{ name: 'PostgreSQL', aceEditorPlugin: 'pgsql' },
	{ name: 'PHP', aceEditorPlugin: 'php' },
	{ name: 'PowerShell', aceEditorPlugin: 'powershell' },
	{ name: 'Praat', aceEditorPlugin: 'praat' },
	{ name: 'Prolog', aceEditorPlugin: 'prolog' },
	{ name: 'Properties', aceEditorPlugin: 'properties' },
	{ name: 'Protobuf', aceEditorPlugin: 'protobuf' },
	{ name: 'Python', aceEditorPlugin: 'python' },
	{ name: 'Razor', aceEditorPlugin: 'razor' },
	{ name: 'RDoc', aceEditorPlugin: 'rdoc' },
	{ name: 'R HTML', aceEditorPlugin: 'rhtml' },
	{ name: 'R', aceEditorPlugin: 'r' },
	{ name: 'RST', aceEditorPlugin: 'rst' },
	{ name: 'Ruby', aceEditorPlugin: 'ruby' },
	{ name: 'Rust', aceEditorPlugin: 'rust' },
	{ name: 'Sass', aceEditorPlugin: 'sass' },
	{ name: 'OpenSCAD', aceEditorPlugin: 'scad' },
	{ name: 'Scala', aceEditorPlugin: 'scala' },
	{ name: 'Scheme', aceEditorPlugin: 'scheme' },
	{ name: 'SCSS', aceEditorPlugin: 'scss' },
	{ name: 'Shell', aceEditorPlugin: 'sh' },
	{ name: 'SJS', aceEditorPlugin: 'sjs' },
	{ name: 'Smarty', aceEditorPlugin: 'smarty' },
	{ name: 'Snippets', aceEditorPlugin: 'snippets' },
	{ name: 'Soy template', aceEditorPlugin: 'soy_template' },
	{ name: 'Whitespace', aceEditorPlugin: 'space' },
	{ name: 'SQL', aceEditorPlugin: 'sql' },
	{ name: 'SQL Server', aceEditorPlugin: 'sqlserver' },
	{ name: 'Stylus', aceEditorPlugin: 'stylus' },
	{ name: 'SVG', aceEditorPlugin: 'svg' },
	{ name: 'Swift', aceEditorPlugin: 'swift' },
	{ name: 'Tcl', aceEditorPlugin: 'tcl' },
	{ name: 'TeX', aceEditorPlugin: 'tex' },
	{ name: 'Textile', aceEditorPlugin: 'textile' },
	{ name: 'TOML', aceEditorPlugin: 'toml' },
	{ name: 'TSX', aceEditorPlugin: 'tsx' },
	{ name: 'Twig', aceEditorPlugin: 'twig' },
	{ name: 'TypeScript', aceEditorPlugin: 'typescript' },
	{ name: 'Vala', aceEditorPlugin: 'vala' },
	{ name: 'VBScript', aceEditorPlugin: 'vbscript' },
	{ name: 'Velocity', aceEditorPlugin: 'velocity' },
	{ name: 'Verilog', aceEditorPlugin: 'verilog' },
	{ name: 'VHDL', aceEditorPlugin: 'vhdl' },
	{ name: 'Wollok', aceEditorPlugin: 'wollok' },
	{ name: 'XML', aceEditorPlugin: 'xml' },
	{ name: 'XQuery', aceEditorPlugin: 'xquery' },
	{ name: 'YAML', aceEditorPlugin: 'yaml' },
	{ name: 'ABAP', aceEditorPlugin: 'abap' },
	{ name: 'ABC', aceEditorPlugin: 'abc' },
	{ name: 'ActionScript', aceEditorPlugin: 'actionscript' },
	{ name: 'Lean', aceEditorPlugin: 'lean' },
	{ name: 'Live Script', aceEditorPlugin: 'live_script' },
	{ name: 'LiveScript', aceEditorPlugin: 'livescript' },
	{ name: 'MavensMate', aceEditorPlugin: 'mavens_mate_log' },
	{ name: 'MIPS Assembly', aceEditorPlugin: 'mips_assembler' },
	{ name: 'MIPSAssembly', aceEditorPlugin: 'mipsassembler' },
	{ name: 'SWIG', aceEditorPlugin: 'swig' },
	{ name: 'Diff', aceEditorPlugin: 'diff' },
	{ name: 'Plain Text', aceEditorPlugin: 'plain_text' },
	{ name: 'Text', aceEditorPlugin: 'text' }
];

var tags = [
	{ name : 'Aaa'},
	{ name : 'Bbb'},
	{ name : 'Ccc'},
	{ name : 'Ddd'},
	{ name : 'Eee'},
	{ name : 'Fff'}
];

var snippets = [
	{
		title: 'Optional description',
		// preview: "console.log('test 1');",
		description: ''
		// parts : snippetParts
	},
	{
		title: 'Public gist.test.py',
		// preview: "console.log('test 2');",
		description: 'test 2 description with **bold text**',
		starred: true,
		// parts : snippetParts
	},
	{
		title: 'Private snippet',
		'private' : true,
		// preview: "console.log('test 3');",
		description: 'test 3 description with **bold text**'
		// parts : snippetParts
	},
	{
		title: 'dTest 4',
		// preview: "console.log('test 4');",
		description: 'test 4 description with **bold text**'
		// parts : snippetParts
	}
];

var users = [
	{
		username: 'test UFO',
    passwordHash: '$2b$10$lHuDgPYu5W8vo7wGemrWoOZDmdvPjrWx83C6cd/Toqut4E7CITY1i',
		email: 'mail@test.com',
		githubUsername: 'UFOcatcher'
	},
	{
		username: 'test',
    passwordHash: '$2b$10$lHuDgPYu5W8vo7wGemrWoOZDmdvPjrWx83C6cd/Toqut4E7CITY1i',
		email: 'usertest@test.com',
		githubUsername: ''
	}
];

module.exports = {snippets : snippets, snippetParts : snippetParts, tags: tags, languages : languages, users: users};
