api:
    prettyPrintJsonResponse: true
    port: 3000
database:
    host: 127.0.0.1
    user: admin
    password: admin_pw
    name: database_name
    dialect: mysql
    fillWithMockData: true
JWT:
    secret: 12345
github:
    clientId: abcde
    clientSecret: abcde
    redirectURI: https://app.com/github-callback/
frontend_url: https://app.com